services:
  - type: web
    name: campeones-django
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn campeones_coquimbo.wsgi:application -b 0.0.0.0:$PORT"
    postDeployCommand: "python manage.py migrate && python manage.py collectstatic --noinput"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: campeones_coquimbo.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"
