services:
  - type: web
    name: campeones-django
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py shell -c \"import os, django; os.environ.setdefault('DJANGO_SETTINGS_MODULE','campeones_coquimbo.settings.production'); django.setup(); from applications.usuarios.models import Usuario; username=os.getenv('INIT_ADMIN_USERNAME','admin'); email=os.getenv('INIT_ADMIN_EMAIL','admin@ejemplo.com'); rut=os.getenv('INIT_ADMIN_RUT','20.756.540-7'); password=os.getenv('INIT_ADMIN_PASSWORD','campeones1'); u, created = Usuario.objects.get_or_create(username=username, defaults={'email':email,'rut':rut,'is_active':True,'is_staff':True,'is_superuser':True}); u.set_password(password); u.save(); print('ADMIN:',u.username,'Password reseted âœ…');\" && gunicorn campeones_coquimbo.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-file - --access-logfile -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: campeones_coquimbo.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: CSRF_TRUSTED_ORIGINS
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: INIT_ADMIN_USERNAME
        value: admin
      - key: INIT_ADMIN_EMAIL
        value: admin@ejemplo.com
      - key: INIT_ADMIN_RUT
        value: "20.756.540-7"
      - key: INIT_ADMIN_PASSWORD
        value: campeones1

databases:
  - name: campeones-db
    plan: free
